export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const FORM_CHECK = 'FORM_CHECK';
export const PRESENT_PROJECT = 'PRESENT_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';

export const TASKS_PROJECT = 'TASKS_PROJECT';
export const ADD_TASKS = 'ADD_TASKS';
export const TASK_CHECK = 'TASK_CHECK';
export const DELETE_TASK = 'DELETE_TASK';
export const PRESENT_TASK = 'PRESENT_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const SUCCESFULL_REGISTRATION = 'SUCCESFULL_REGISTRATION'
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION'
export const GET_USER = 'GET_USER'
export const SUCCESFULL_LOGIN = 'SUCCESFULL_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const LOGOUT = 'LOGOUT'